export const START_FETCHING_SCRIPTS = 'START_FETCHING_SCRIPTS';
export const FETCH_SCRIPTS = 'FETCH_SCRIPTS';
export const FETCH_SCRIPT = 'FETCH_SCRIPT';
export const START_EXECUTING_SCRIPTS = 'START_EXECUTING_SCRIPTS';
export const EXECUTE_SCRIPT = 'EXECUTE_SCRIPT';
